name: docker

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - build
      - Dockerfile
      - env.yaml

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v4

    # Uncomment this if you are building for a non-native --platform
    # - uses: docker/setup-qemu-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: |
        version_tag="ghcr.io/${{ github.repository }}:${{ github.run_id }}"
        latest_tag="ghcr.io/${{ github.repository }}:latest"
        ./build \
          --tag "$version_tag" \
          --tag "$latest_tag" \
          --push

        cat >"$GITHUB_STEP_SUMMARY" <<~~
        Image successfully published.

        Pull the image for local use:

            docker pull $version_tag

        or

            docker pull $latest_tag
        ~~
