name: docker

on:
  push:
    paths:
      - .github/workflows/docker.yml
      - build
      - Dockerfile

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

    - uses: actions/checkout@v4

    # Uncomment this if you are building for a non-native --platform
    # - uses: docker/setup-qemu-action@v3

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      run: |
        image_tag="ghcr.io/${{ github.repository }}:${{ github.run_id }}"
        ./build \
          --tag "$image_tag" \
          --push

        cat >"$GITHUB_STEP_SUMMARY" <<~~
        Image successfully published.

        Pull the image for local use:

            docker pull $image_tag
        ~~
